# 数据预处理

---

创建包含更多行和列的原始数据集。

In [ ]:
import os
import pandas as pd

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('id,MSSubClass,MSZoning,LotFrontage,NumRooms,Alley,Price\n')  # 列名
    f.write('1,60,RL,65,NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,70,NA,70,2,NA,106000\n')
    f.write('3,NA,NA,80,4,NA,178100\n')
    f.write('4,NA,NA,90,NA,NA,140000\n')
    
original_data = pd.read_csv(data_file)
original_data

   id  MSSubClass MSZoning  LotFrontage  NumRooms Alley   Price
0   1        60.0       RL           65       NaN  Pave  127500
1   2        70.0      NaN           70       2.0   NaN  106000
2   3         NaN      NaN           80       4.0   NaN  178100
3   4         NaN      NaN           90       NaN   NaN  140000

---

## 练习2.2.1

删除缺失值最多的列。

### &emsp;解答：

&emsp;&emsp;通过观察，可以看到 MSZoning 和 Alley 列的缺失值一样多，需要考虑到缺失值最多的列有多个的情况使用`original_data.isna().sum()[original_data.isna().sum() == original_data.isna().sum().max()].index.tolist()`得到最多缺失值的列名, 再进行删除。

In [ ]:
original_data.isna().sum()[original_data.isna().sum() == original_data.isna().sum().max()].index.tolist()

['MSZoning', 'Alley']

In [ ]:
data = original_data.drop(original_data.isna().sum()[original_data.isna().sum() == original_data.isna().sum().max()].index.tolist(), axis=1)
data

   id  MSSubClass  LotFrontage  NumRooms   Price
0   1        60.0           65       NaN  127500
1   2        70.0           70       2.0  106000
2   3         NaN           80       4.0  178100
3   4         NaN           90       NaN  140000

---

## 练习2.2.2

将预处理后的数据集转换为张量格式。

### &emsp;解答：

&emsp;&emsp;使用`torch.tensor`方法，将数据集转换为张量格式。

In [ ]:
# 将Alley列转换成one-hot编码
data = pd.get_dummies(data, dummy_na=True)
data

   id  MSSubClass  LotFrontage  NumRooms   Price  Alley_Pave  Alley_nan
0   1        60.0           65       NaN  127500           1          0
1   2        70.0           70       2.0  106000           0          1
2   3         NaN           80       4.0  178100           0          1
3   4         NaN           90       NaN  140000           0          1

In [ ]:
# 将数据集转换为张量格式
data=torch.tensor(data.values)
data

tensor([[1.0000e+00, 6.0000e+01, 6.5000e+01,        nan, 1.2750e+05, 1.0000e+00,
         0.0000e+00],
        [2.0000e+00, 7.0000e+01, 7.0000e+01, 2.0000e+00, 1.0600e+05, 0.0000e+00,
         1.0000e+00],
        [3.0000e+00,        nan, 8.0000e+01, 4.0000e+00, 1.7810e+05, 0.0000e+00,
         1.0000e+00],
        [4.0000e+00,        nan, 9.0000e+01,        nan, 1.4000e+05, 0.0000e+00,
         1.0000e+00]], dtype=torch.float64)